name: cat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  surf_lint_rules: ^2.0.0
  webview_flutter: ^4.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
